name: drifting_robotics
channels:
  - pytorch
  - conda-forge
  - pytorch3d
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1.0
  - torchvision
  - numpy
  - scipy
  - numba
  - pytorch3d
  - scikit-image
  - scikit-video
  - imageio
  - imageio-ffmpeg
  - av
  - cmake=3.5
  - pip
  - pip:
    - robomimic
    - gym==0.26.2
    - pygame
    - pymunk
    - shapely
    - zarr
    - diffusers
    - tqdm
    - matplotlib
    - h5py
    - hydra-core
    - omegaconf
    - dill
    - einops